plugins {
    id 'java-library'
    id 'signing'
    id 'maven-publish'
    alias(libs.plugins.catalogUpdater)
    alias(libs.plugins.reckon)
    alias(libs.plugins.sentry)
}

group = 'fr.anisekai'

apply from: 'gradle/java.gradle'
apply from: 'gradle/reckon.gradle'

project.afterEvaluate {
    apply from: 'gradle/publication.gradle'
}

repositories {
    mavenCentral()
    mavenLocal()
}

configurations {
    mockitoAgent
}

dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platformLauncher

    testImplementation libs.bundles.mockito

    mockitoAgent(libs.mockito.core) {
        transitive = false
    }

    api(libs.jetbrains.annotations)

    api(libs.anisekai.ffmpeg)
    api(libs.anisekai.scheduler)
    api(libs.jackson.databind)

    implementation(libs.uuid)
}

test {
    useJUnitPlatform()
}

tasks {
    test {
        jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
    }
}

// Required by Sentry Gradle plugin — assume these tasks are defined elsewhere
tasks.named('sourcesJar') {
    dependsOn tasks.named('generateSentryDebugMetaPropertiesjava')
    dependsOn tasks.named('collectExternalDependenciesForSentry')
}
