plugins {
    id 'java-library'
    id 'signing'
    id 'maven-publish'
    alias(libs.plugins.catalogUpdater)
    alias(libs.plugins.reckon)
    alias(libs.plugins.sentry)
}

group = 'fr.anisekai'

apply from: 'gradle/java.gradle'
apply from: 'gradle/reckon.gradle'

project.afterEvaluate {
    apply from: 'gradle/publication.gradle'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platformLauncher

    implementation(libs.alexpado.simpleHttpClient)
    implementation(libs.json.json)
    implementation(libs.rometools.rome)

    implementation(libs.jetbrains.annotations)
    implementation(libs.orm.hibernate)
}

test {
    useJUnitPlatform()
}

// Required by Sentry Gradle plugin — assume these tasks are defined elsewhere
tasks.named('sourcesJar') {
    dependsOn tasks.named('generateSentryDebugMetaPropertiesjava')
    dependsOn tasks.named('collectExternalDependenciesForSentry')
}
